# Job Scheduler Configuration
# This file can be overridden by environment variables with JOB_SCHEDULER_ prefix
# Example: JOB_SCHEDULER_DATABASE_HOST=localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: job_scheduler
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

server:
  host: 0.0.0.0
  port: 8080
  mode: debug  # debug, release, test

scheduler:
  poll_interval: 5s      # How often to check for ready jobs
  batch_size: 100        # Max jobs to process in one batch
  http_timeout: 30s      # HTTP timeout for external calls

worker:
  pool_size: 10          # Number of concurrent workers
  http_timeout: 90s      # HTTP timeout for job execution
  retry_delay: 10s       # Delay between retries
  max_retries: 3         # Maximum number of retries

logging:
  level: info            # debug, info, warn, error
  format: json           # json, text
